#ifndef DIALOG_TICKET_H
#define DIALOG_TICKET_H

#include <QDialog>

namespace Ui {
class Dialog_Ticket;
}

/**
 * @brief Displays the details of a selected ticket.
 *
 * This dialog displays the general information of a ticket,
 * including its ID, ticket number, sale date, and total amount.
 * It also displays the products included in the ticket.
 */
class Dialog_Ticket : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the ticket details dialog.
     *
     * Initializes the dialog using the specified ticket number.
     *
     * @param ticketNumber Ticket number whose details will be displayed.
     * @param parent Parent widget of the dialog.
     */
    explicit Dialog_Ticket(
        int ticketNumber,
        QWidget *parent = nullptr);

    /**
     * @brief Destroys the ticket details dialog.
     */
    ~Dialog_Ticket();

private:

    /* User interface generated by Qt Designer */
    Ui::Dialog_Ticket *ui;

    /* Ticket number used to retrieve the ticket information */
    int m_ticketNumber;
};

#endif // DIALOG_TICKET_H