#include <QDialog>
#include "../statistics/sales_statistics.h"

namespace Ui {
class Dialog_SaleChart;
}

/**
 * @brief Dialog used to display sales and profit statistics.
 *
 * Displays daily sales totals and gross profits in a bar chart
 * based on the selected date range.
 */
class Dialog_SaleChart : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the sales chart dialog.
     *
     * @param data List of daily sales statistics used to generate
     *             the sales and profit chart.
     * @param parent Parent widget of the dialog.
     */
    explicit Dialog_SaleChart(
        const QList<DailySales>& data,
        const QList<ProductSales>& productSales,
        QWidget *parent = nullptr);

    /**
     * @brief Destroys the sales chart dialog.
     */
    ~Dialog_SaleChart();

private:

    /**
     * @brief UI generated by Qt Designer.
     */
    Ui::Dialog_SaleChart *ui;

    /**
     * @brief Daily sales statistics used to generate the chart.
     */
    QList<DailySales> m_data;

    /**
     * @brief Stores product sales statistics used to generate the product chart.
     */
    QList<ProductSales> m_productSales;
};