#ifndef DIALOG_PAYMENT_H
#define DIALOG_PAYMENT_H

#include <QDialog>

namespace Ui {
class Dialog_Payment;
}

/**
 * @class Dialog_Payment
 * @brief Provides the payment interface for completing a sale transaction.
 *
 * This dialog allows the user to enter the amount received from the customer,
 * calculates the change to return, and validates that the payment is enough
 * to complete the transaction.
 *
 * The dialog receives the total sale amount through the constructor and
 * returns payment information using getter functions.
 */
class Dialog_Payment : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs a payment dialog.
     *
     * Initializes the dialog with the total amount of the current sale.
     *
     * @param total Total amount to be paid.
     * @param parent Parent widget.
     */
    explicit Dialog_Payment(double total, QWidget *parent = nullptr);


    /**
     * @brief Destructor of Dialog_Payment.
     *
     * Releases the UI resources allocated for the dialog.
     */
    ~Dialog_Payment();


    /**
     * @brief Gets the amount received from the customer.
     *
     * @return Customer payment amount.
     */
    double getPayment() const;


    /**
     * @brief Gets the calculated change amount.
     *
     * @return Change to return to the customer.
     */
    double getChange() const;


private slots:

    /**
     * @brief Handles the confirmation button click event.
     *
     * Reads the entered payment amount, calculates the change,
     * and accepts the dialog if the payment is sufficient.
     */
    void on_pushButton_Confirm_clicked();


private:

    /**
     * @brief UI components generated by Qt Designer.
     */
    Ui::Dialog_Payment *ui;


    /**
     * @brief Total amount of the current sale.
     */
    double m_total;


    /**
     * @brief Amount received from the customer.
     */
    double m_payment;


    /**
     * @brief Amount of change to return to the customer.
     */
    double m_change;
};

#endif // DIALOG_PAYMENT_H